### ISSUE TITLE
Sell/Buy Test 

### ISSUE THREAD

**Issue by mehrdadmms** [pattern-tech/gateway#12]
# Task

- [ ] Flow document for manual tests
- [ ] Unit test for Execution
- [ ] Unit test for estimation
- [ ] Manual test for execution/estimation
