### ISSUE TITLE
Gateway

### ISSUE THREAD

**Issue by mehrdadmms** [pattern-tech/gateway#18]
# Tasks
- [x]  Clean up code
- [ ] Documentation for function
  - [ ] Execution for Buy/Sell
  - [ ] Chain missing documents
  - [ ] Estimate sell/buy
