### ISSUE TITLE
Create wallet

### ISSUE THREAD

**Issue by mehrdadmms** [pattern-tech/gateway#21]
# Task

- [ ] Get secret key
- [ ] Create a document for the user on how to receive secret key and use it
- [ ] Create a function for the user to create own wallet
- [ ] Withdraw from the created wallet
